# Configuration File for morph_stats application

---

##############################################

neurite:
    section_lengths:
        - max
        - sum
    section_volumes:
        - sum
    section_branch_orders:
        - max

neurite_type:
    - AXON
    - APICAL_DENDRITE
    - BASAL_DENDRITE
    - ALL

morphology:
    soma_radius:
        - mean

##############################################
